name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker images
        run: |
          docker build -t udagram-api-feed ./udagram-api-feed
          docker tag udagram-api-feed ${{ secrets.DOCKER_USERNAME }}/udagram-api-feed:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-api-feed:v1
          docker build -t udagram-api-user ./udagram-api-user
          docker tag udagram-api-user ${{ secrets.DOCKER_USERNAME }}/udagram-api-user:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-api-user:v1
          docker build -t udagram-frontend ./udagram-frontend
          docker tag udagram-frontend ${{ secrets.DOCKER_USERNAME }}/udagram-frontend:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-frontend:v1
          docker build -t udagram-reverseproxy ./udagram-reverseproxy
          docker tag udagram-reverseproxy ${{ secrets.DOCKER_USERNAME }}/udagram-reverseproxy:v1
          docker push ${{ secrets.DOCKER_USERNAME }}/udagram-reverseproxy:v1
